// <auto-generated />
using System;
using FirstWebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180915110438_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleAppWithDb.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Clents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "0556566611",
                            Name = "Vlad"
                        });
                });

            modelBuilder.Entity("ConsoleAppWithDb.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("InstitutionId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Пельмени1Пельмени1",
                            InstitutionId = 2,
                            Name = "Пельмени1",
                            Price = 100.0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Пельмени2Пельмени2",
                            InstitutionId = 3,
                            Name = "Пельмени2",
                            Price = 200.0m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Пельмени3Пельмени3",
                            InstitutionId = 2,
                            Name = "Пельмени3",
                            Price = 300.0m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Пельмени4Пельмени4",
                            InstitutionId = 1,
                            Name = "Пельмени4",
                            Price = 400.0m
                        });
                });

            modelBuilder.Entity("ConsoleAppWithDb.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "cafe1",
                            Name = "Кафе1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "cafe2",
                            Name = "Кафе2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "cafe3",
                            Name = "Кафе3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "cafe4",
                            Name = "Кафе4"
                        });
                });

            modelBuilder.Entity("ConsoleAppWithDb.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CafeId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DishId");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CafeId = 0,
                            Date = new DateTime(1997, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
